maint: add doc deploying

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -150,19 +150,27 @@ jobs:
             --namespace="$KUBE_NAMESPACE" \
             --dry-run=client -o yaml | kubectl apply -f -
 
-      - name: Create GitHub doc token secret
+      - name: Create GitHub app secret
         if: github.event_name == 'release'
         env:
-          DOCS_GITHUB_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}
+          GH_APP_ID: ${{ secrets.GH_APP_ID }}
+          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
+          GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
           KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
         run: |
-          if [ -z "$DOCS_GITHUB_TOKEN" ]; then
-            echo "::error::Missing DOCS_GITHUB_TOKEN secret for documentation branch pushes."
+          if [ -z "$GH_APP_ID" ]; then
+            echo "::error::Missing GH_APP_ID secret for documentation branch pushes."
+            exit 1
+          fi
+          if [ -z "$GH_APP_PRIVATE_KEY" ]; then
+            echo "::error::Missing GH_APP_PRIVATE_KEY secret for documentation branch pushes."
             exit 1
           fi
 
-          kubectl create secret generic github-doc-token \
-            --from-literal=DOCS_GITHUB_TOKEN="$DOCS_GITHUB_TOKEN" \
+          kubectl create secret generic github-app \
+            --from-literal=GH_APP_ID="$GH_APP_ID" \
+            --from-literal=GH_APP_PRIVATE_KEY="$GH_APP_PRIVATE_KEY" \
+            --from-literal=GH_APP_INSTALLATION_ID="$GH_APP_INSTALLATION_ID" \
             --namespace="$KUBE_NAMESPACE" \
             --dry-run=client -o yaml | kubectl apply -f -
 
